// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleRecipeSite.Data;

#nullable disable

namespace SimpleRecipeSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505115954_InitialRecipes")]
    partial class InitialRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleRecipeSite.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("CookMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_minutes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_minutes");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Breakfast",
                            CookMinutes = 15,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A simple family breakfast recipe.",
                            Ingredients = "2 eggs\n200 ml milk\n150 g flour\n1 tsp baking powder\n1 pinch salt\nButter for frying",
                            Instructions = "Whisk eggs and milk.\nMix dry ingredients, then combine with wet ingredients.\nCook in a buttered pan until golden on both sides.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Family recipe",
                            Title = "Pancakes",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Breakfast",
                            CookMinutes = 10,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm oats with fruit and cinnamon.",
                            Ingredients = "80 g oats\n400 ml milk\n1 apple\n1 tsp cinnamon",
                            Instructions = "Simmer oats in milk.\nStir in chopped apple and cinnamon.\nServe warm.",
                            PrepMinutes = 5,
                            Servings = 2,
                            Source = "Weekday staple",
                            Title = "Oatmeal With Apple",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Breakfast",
                            CookMinutes = 6,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft eggs for a quick start.",
                            Ingredients = "4 eggs\n2 tbsp milk\nSalt\nButter",
                            Instructions = "Whisk eggs with milk.\nCook gently in butter while stirring.\nSeason and serve.",
                            PrepMinutes = 5,
                            Servings = 2,
                            Source = "Family basics",
                            Title = "Scrambled Eggs",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Breakfast",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "No-cook breakfast bowl.",
                            Ingredients = "300 g yogurt\n1 cup berries\n2 tbsp nuts\n1 tbsp honey",
                            Instructions = "Add yogurt to bowls.\nTop with berries, nuts, and honey.\nServe immediately.",
                            PrepMinutes = 5,
                            Servings = 2,
                            Source = "Summer breakfast",
                            Title = "Yogurt Berry Bowl",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Soup",
                            CookMinutes = 25,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple smooth tomato soup.",
                            Ingredients = "1 onion\n2 cloves garlic\n800 g canned tomatoes\n500 ml stock",
                            Instructions = "Saute onion and garlic.\nAdd tomatoes and stock.\nSimmer and blend.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Weeknight dinner",
                            Title = "Tomato Soup",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Soup",
                            CookMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comforting broth with noodles.",
                            Ingredients = "1 onion\n2 carrots\n200 g chicken\n1.2 l stock\n120 g noodles",
                            Instructions = "Cook vegetables in pot.\nAdd stock and chicken, simmer.\nShred chicken and add noodles until tender.",
                            PrepMinutes = 15,
                            Servings = 4,
                            Source = "Cold-weather meal",
                            Title = "Chicken Noodle Soup",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Soup",
                            CookMinutes = 35,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hearty pantry soup.",
                            Ingredients = "1 cup lentils\n1 onion\n2 carrots\n1.2 l stock\n1 tsp cumin",
                            Instructions = "Saute vegetables.\nAdd lentils, stock, and cumin.\nSimmer until lentils are tender.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Pantry recipe",
                            Title = "Lentil Soup",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Soup",
                            CookMinutes = 20,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy mushroom soup without fuss.",
                            Ingredients = "400 g mushrooms\n1 onion\n20 g butter\n500 ml stock\n100 ml cream",
                            Instructions = "Cook onion and mushrooms in butter.\nAdd stock and simmer.\nBlend partly, then stir in cream.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Family notebook",
                            Title = "Mushroom Soup",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Dinner",
                            CookMinutes = 75,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One-tray chicken and vegetables.",
                            Ingredients = "1 whole chicken\n600 g potatoes\n3 carrots\n2 tbsp oil\nSalt and pepper",
                            Instructions = "Season chicken and vegetables.\nRoast until chicken is cooked through.\nRest before serving.",
                            PrepMinutes = 15,
                            Servings = 4,
                            Source = "Sunday dinner",
                            Title = "Roast Chicken Tray",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dinner",
                            CookMinutes = 35,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic meat sauce pasta.",
                            Ingredients = "400 g minced beef\n1 onion\n2 garlic cloves\n400 g tomatoes\n300 g spaghetti",
                            Instructions = "Brown beef with onion and garlic.\nAdd tomatoes and simmer.\nCook spaghetti and serve with sauce.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Family favorite",
                            Title = "Spaghetti Bolognese",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dinner",
                            CookMinutes = 12,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast vegetable dinner.",
                            Ingredients = "1 broccoli\n1 pepper\n2 carrots\n2 tbsp soy sauce\n1 tbsp oil",
                            Instructions = "Slice vegetables.\nStir fry on high heat.\nAdd soy sauce and serve with rice.",
                            PrepMinutes = 10,
                            Servings = 3,
                            Source = "Quick dinner list",
                            Title = "Vegetable Stir Fry",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Dinner",
                            CookMinutes = 18,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple lemon salmon.",
                            Ingredients = "4 salmon fillets\n1 lemon\n1 tbsp olive oil\nSalt\nPepper",
                            Instructions = "Season salmon and add lemon slices.\nBake until flaky.\nServe with potatoes or salad.",
                            PrepMinutes = 8,
                            Servings = 4,
                            Source = "Weeknight fish",
                            Title = "Baked Salmon",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Lunch",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quick lunch sandwich.",
                            Ingredients = "4 slices bread\n120 g turkey\nLettuce\nTomato\nMustard",
                            Instructions = "Toast bread if desired.\nLayer turkey, lettuce, and tomato.\nSpread mustard and close sandwich.",
                            PrepMinutes = 7,
                            Servings = 2,
                            Source = "Work lunch",
                            Title = "Turkey Sandwich",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Lunch",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bright salad with chickpeas.",
                            Ingredients = "1 can chickpeas\n1 cucumber\n2 tomatoes\n2 tbsp olive oil\n1 tbsp lemon juice",
                            Instructions = "Drain chickpeas and chop vegetables.\nMix with oil and lemon.\nSeason and serve.",
                            PrepMinutes = 12,
                            Servings = 3,
                            Source = "Light lunch",
                            Title = "Chickpea Salad",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Lunch",
                            CookMinutes = 12,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cold pasta lunch.",
                            Ingredients = "250 g pasta\n1 can tuna\n1 cup peas\n2 tbsp mayo\n1 tbsp lemon juice",
                            Instructions = "Cook and cool pasta.\nMix tuna, peas, mayo, and lemon.\nCombine and chill briefly.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Picnic recipe",
                            Title = "Tuna Pasta Salad",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Category = "Lunch",
                            CookMinutes = 4,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Open sandwich with basil.",
                            Ingredients = "4 slices bread\n2 tomatoes\n125 g mozzarella\nBasil\nOlive oil",
                            Instructions = "Toast bread.\nTop with tomato and mozzarella.\nFinish with basil and olive oil.",
                            PrepMinutes = 8,
                            Servings = 2,
                            Source = "Summer lunch",
                            Title = "Tomato Mozzarella Toast",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Category = "Baking",
                            CookMinutes = 50,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moist loaf for snack time.",
                            Ingredients = "3 ripe bananas\n2 eggs\n180 g flour\n100 g sugar\n1 tsp baking soda",
                            Instructions = "Mash bananas and mix with eggs.\nStir in dry ingredients.\nBake until golden.",
                            PrepMinutes = 10,
                            Servings = 8,
                            Source = "Grandma's notes",
                            Title = "Banana Bread",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Category = "Baking",
                            CookMinutes = 14,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple afternoon scones.",
                            Ingredients = "300 g flour\n2 tsp baking powder\n75 g butter\n150 ml milk",
                            Instructions = "Rub butter into flour.\nAdd milk to form dough.\nCut rounds and bake.",
                            PrepMinutes = 12,
                            Servings = 8,
                            Source = "Tea-time recipe",
                            Title = "Scones",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Category = "Baking",
                            CookMinutes = 25,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft rolls with cinnamon filling.",
                            Ingredients = "500 g flour\n250 ml milk\n7 g yeast\n80 g sugar\n2 tsp cinnamon",
                            Instructions = "Mix dough and let rise.\nFill with sugar and cinnamon.\nRoll, slice, and bake.",
                            PrepMinutes = 25,
                            Servings = 10,
                            Source = "Weekend baking",
                            Title = "Cinnamon Rolls",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Category = "Baking",
                            CookMinutes = 40,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic everyday loaf.",
                            Ingredients = "500 g whole wheat flour\n350 ml water\n7 g yeast\n1 tsp salt",
                            Instructions = "Knead dough and let rise.\nShape loaf and proof.\nBake until crusty.",
                            PrepMinutes = 20,
                            Servings = 10,
                            Source = "Daily bread",
                            Title = "Whole Wheat Bread",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Category = "Dessert",
                            CookMinutes = 10,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quick stovetop dessert.",
                            Ingredients = "500 ml milk\n40 g cocoa powder\n60 g sugar\n30 g cornstarch",
                            Instructions = "Whisk all ingredients cold.\nCook while stirring until thick.\nChill before serving.",
                            PrepMinutes = 8,
                            Servings = 4,
                            Source = "Family dessert",
                            Title = "Chocolate Pudding",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Category = "Dessert",
                            CookMinutes = 35,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm apples under crunchy topping.",
                            Ingredients = "6 apples\n120 g flour\n80 g sugar\n80 g butter\n1 tsp cinnamon",
                            Instructions = "Slice apples and season.\nRub crumble topping ingredients.\nBake until bubbling and golden.",
                            PrepMinutes = 15,
                            Servings = 6,
                            Source = "Autumn favorite",
                            Title = "Apple Crumble",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Category = "Dessert",
                            CookMinutes = 70,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy baked rice pudding.",
                            Ingredients = "120 g short-grain rice\n1 l milk\n60 g sugar\n1 tsp vanilla",
                            Instructions = "Mix ingredients in baking dish.\nBake slowly, stirring once.\nServe warm or cold.",
                            PrepMinutes = 10,
                            Servings = 6,
                            Source = "Old cookbook",
                            Title = "Rice Pudding",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Category = "Dessert",
                            CookMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tangy bars with short crust.",
                            Ingredients = "150 g flour\n90 g butter\n180 g sugar\n2 eggs\n2 lemons",
                            Instructions = "Bake crust first.\nWhisk lemon filling and pour over crust.\nBake again and cool.",
                            PrepMinutes = 15,
                            Servings = 12,
                            Source = "Bake sale",
                            Title = "Lemon Bars",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Category = "Sides",
                            CookMinutes = 20,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy mashed potatoes.",
                            Ingredients = "1 kg potatoes\n40 g butter\n120 ml milk\nSalt",
                            Instructions = "Boil potatoes until tender.\nMash with butter and milk.\nSeason well.",
                            PrepMinutes = 10,
                            Servings = 4,
                            Source = "Dinner side",
                            Title = "Mashed Potatoes",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Category = "Sides",
                            CookMinutes = 25,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet oven-roasted carrots.",
                            Ingredients = "600 g carrots\n1 tbsp oil\nSalt\nPepper",
                            Instructions = "Slice carrots and season.\nRoast until browned at edges.\nServe warm.",
                            PrepMinutes = 8,
                            Servings = 4,
                            Source = "Sheet pan side",
                            Title = "Roasted Carrots",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Category = "Sides",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh and simple salad.",
                            Ingredients = "1 cucumber\n2 tbsp yogurt\n1 tbsp vinegar\nDill",
                            Instructions = "Slice cucumber thinly.\nMix dressing ingredients.\nToss and chill briefly.",
                            PrepMinutes = 8,
                            Servings = 3,
                            Source = "Summer table",
                            Title = "Cucumber Salad",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Category = "Sides",
                            CookMinutes = 10,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pan-tossed green beans.",
                            Ingredients = "400 g green beans\n2 cloves garlic\n1 tbsp olive oil\nSalt",
                            Instructions = "Blanch green beans.\nSaute garlic in oil.\nToss beans and season.",
                            PrepMinutes = 8,
                            Servings = 4,
                            Source = "Weeknight side",
                            Title = "Garlic Green Beans",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Category = "Preserves",
                            CookMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Small-batch fruit preserve.",
                            Ingredients = "1 kg strawberries\n700 g sugar\n2 tbsp lemon juice",
                            Instructions = "Cook strawberries with sugar.\nSimmer until jammy.\nJar while hot.",
                            PrepMinutes = 15,
                            Source = "Summer preserving",
                            Title = "Strawberry Jam",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Category = "Preserves",
                            CookMinutes = 5,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crunchy quick pickles.",
                            Ingredients = "2 cucumbers\n250 ml vinegar\n250 ml water\n2 tbsp sugar\n1 tbsp salt",
                            Instructions = "Slice cucumbers.\nBoil brine ingredients.\nPour over cucumbers and cool.",
                            PrepMinutes = 10,
                            Source = "Pantry shelf",
                            Title = "Pickled Cucumbers",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Category = "Preserves",
                            CookMinutes = 35,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet-spiced chutney.",
                            Ingredients = "800 g peaches\n1 onion\n150 ml vinegar\n100 g sugar\n1 tsp ginger",
                            Instructions = "Chop peaches and onion.\nCook with remaining ingredients.\nSimmer until thick.",
                            PrepMinutes = 15,
                            Source = "Late summer batch",
                            Title = "Peach Chutney",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            CookMinutes = 12,
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light pasta with fresh herbs.",
                            Ingredients = "300 g pasta\n2 tbsp olive oil\n2 cloves garlic\nParsley\nBasil",
                            Instructions = "Cook pasta.\nWarm oil with garlic.\nToss pasta with herbs and season.",
                            PrepMinutes = 10,
                            Servings = 3,
                            Source = "Garden season",
                            Title = "Garden Herb Pasta",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
