// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleRecipeSite.Data;

#nullable disable

namespace SimpleRecipeSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508062023_InitialRecipes")]
    partial class InitialRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleRecipeSite.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("execution");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients");

                    b.Property<string>("Introduction")
                        .HasColumnType("text")
                        .HasColumnName("introduction");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("Preparation")
                        .HasColumnType("text")
                        .HasColumnName("preparation");

                    b.Property<string>("Reflection")
                        .HasColumnType("text")
                        .HasColumnName("reflection");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TimeEstimate")
                        .HasColumnType("text")
                        .HasColumnName("time_estimate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Variation")
                        .HasColumnType("text")
                        .HasColumnName("variation");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Breakfast",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Execution = "Melt butter over gentle heat.\nAdd beaten eggs and stir slowly, scraping the base often.\nTake the pan off heat while the eggs still look slightly underdone.\nResidual heat will finish them.\nTaste, then salt.",
                            Ingredients = "2 to 3 eggs per person\nA small knob of butter\nFine salt",
                            Introduction = "Most scrambled eggs are overcooked into rubber and regret. The dish is simple, which means every choice matters.",
                            Objective = "A soft, decadent scramble that still tastes unmistakably like egg.",
                            Preparation = "Use a small saucepan and a flexible spatula. Keep salt nearby. Start with less butter than you think and adjust next time.",
                            Reflection = "If the eggs tightened too quickly, your heat was too high. If they turned dry, you cooked a minute too long. Next batch: lower heat, earlier stop.",
                            Slug = "scrambled-eggs",
                            Source = "Kitchen notes",
                            TimeEstimate = "About 10 minutes",
                            Title = "Scrambled Eggs",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variation = "Better eggs improve flavor immediately.\nA spoon of creme fraiche at the end gives extra silk.\nFresh chives and black pepper are optional, not mandatory."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Soup",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Execution = "Cook onion gently in oil until soft.\nAdd garlic briefly.\nAdd tomatoes and stock, then simmer until integrated.\nBlend smooth or leave rustic.\nSeason in small steps.",
                            Ingredients = "1 onion\n2 garlic cloves\n1 can whole tomatoes\nStock or water\nOlive oil\nSalt",
                            Introduction = "Tomato soup should feel bright and comforting at once, not flat or sweet.",
                            Objective = "A balanced soup with acidity, body, and warmth.",
                            Preparation = "Slice onion and garlic before heating the pot. Keep a little stock aside for adjusting thickness later.",
                            Reflection = "If it tastes dull, it usually needs salt first, then a touch of acidity. If too sharp, simmer longer.",
                            Slug = "tomato-soup",
                            Source = "Family notebook",
                            TimeEstimate = "30 to 40 minutes",
                            Title = "Tomato Soup",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variation = "Finish with cream for a softer bowl, or add chili for heat."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dinner",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Execution = "Heat oven well before loading.\nToss vegetables with oil and seasoning.\nPlace chicken skin-side up with space between pieces.\nRoast until chicken is cooked and vegetables caramelized.\nRest before serving.",
                            Ingredients = "Chicken pieces\nPotatoes\nCarrots\nOlive oil\nSalt and pepper",
                            Introduction = "A tray roast is less about precision and more about sequencing and heat.",
                            Objective = "Juicy chicken with properly cooked vegetables in one pass.",
                            Preparation = "Cut vegetables to similar size. Pat chicken dry so it roasts instead of steams.",
                            Reflection = "Crowding the tray causes steaming. If vegetables lag behind, spread them out and give more high heat.",
                            Slug = "roast-chicken-tray",
                            Source = "Sunday routine",
                            TimeEstimate = "About 1 hour",
                            Title = "Roast Chicken Tray",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variation = "Swap carrots for fennel or onions. Lemon and thyme change the profile quickly."
                        },
                        new
                        {
                            Id = 4,
                            Category = "Preserves",
                            CreatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Execution = "Cook berries and sugar until dissolved.\nAdd lemon juice and simmer steadily.\nSkim foam if needed.\nTest set on the cold plate.\nJar while hot.",
                            Ingredients = "Strawberries\nSugar\nLemon juice",
                            Introduction = "Jam is about controlling moisture and timing, not just boiling fruit.",
                            Objective = "A spoonable jam that still tastes fresh.",
                            Preparation = "Wash and hull berries. Warm jars while cooking. Keep a cold plate in the freezer for set testing.",
                            Reflection = "Underset jam needs longer simmer. Overcooked jam tastes dull and sticky.",
                            Slug = "strawberry-jam",
                            Source = "Summer preserve book",
                            TimeEstimate = "45 to 60 minutes",
                            Title = "Strawberry Jam",
                            UpdatedAtUtc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variation = "A little black pepper or vanilla changes the finish without hiding the fruit."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
